schema_version: 1
environment: dev
updated_at: "2026-06-23"
protocol:
    name: xarb
    release: v0.1.0
hub:
    chain_id: 421614
    name: arbitrum-sepolia
    role: hub
    native_symbol: ETH
    explorer_url: https://sepolia.arbiscan.io
    deployment_block: 12345678
    contracts:
        hub:
            address: 0x7218432FaBCDdadA0a8a4a18991D1F7B90F84Ba8
        oracle:
            address: 0xb6C67166Adc4D7887119B339696e69b16e38eC43
spokes:
    - chain_id: 11155111
      name: sepolia
      role: spoke
      native_symbol: ETH
      explorer_url: https://sepolia.etherscan.io
      deployment_block: 12345678
      contracts:
        faucet_dispenser:
            address: "0x0000000000000000000000000000000000000000"
        lending_pool:
            address: 0x7Ea32b993F260cfB9c8ECCf35eB03a3D0229E18D
        spoke:
            address: 0x2E6d21E5C780A31861373a599665E63a49767F91
      substreams:
        start_block: 0
    - chain_id: 421614
      name: arbitrum-sepolia
      role: spoke
      native_symbol: ETH
      explorer_url: https://sepolia.arbiscan.io
      deployment_block: 12345678
      contracts:
        faucet_dispenser:
            address: "0x0000000000000000000000000000000000000000"
        lending_pool:
            address: 0x97bcB5F1c66B8B0BcfbdC22350f0fB1F3ec5993a
        spoke:
            address: 0x86dC3e07e852180c9751e187134B75177A6D3244
      substreams:
        start_block: 0
