schema_version: 1
environment: dev
updated_at: "2026-06-24"
protocol:
    name: xarb
    release: v0.1.0
hub:
    chain_id: 421614
    name: arbitrum-sepolia
    role: hub
    native_symbol: ETH
    explorer_url: https://sepolia.arbiscan.io
    deployment_block: 12345678
    contracts:
        hub:
            address: "0x143e151342d5EA919bFD4d21E7665459f61EEcd1"
        oracle:
            address: "0x80d61662c88f984B1402213E45442fa2E5c1FCd0"
spokes:
    - chain_id: 11155111
      name: sepolia
      role: spoke
      native_symbol: ETH
      explorer_url: https://sepolia.etherscan.io
      deployment_block: 12345678
      contracts:
        faucet_dispenser:
            address: "0x0000000000000000000000000000000000000000"
        lending_pool:
            address: "0x1A17516C63CAAF67f95E8ad89d709417AefF438f"
        spoke:
            address: "0xe89E859D81691961077e235c73b36f86CED30061"
      substreams:
        start_block: 0
    - chain_id: 421614
      name: arbitrum-sepolia
      role: spoke
      native_symbol: ETH
      explorer_url: https://sepolia.arbiscan.io
      deployment_block: 12345678
      contracts:
        faucet_dispenser:
            address: "0x0000000000000000000000000000000000000000"
        lending_pool:
            address: "0x3c1702861136758A20b6F9aD10dc19CA7065BD24"
        spoke:
            address: "0x10f9DDdC83D99E94c3e5f24496950Cf2C5DE9beC"
      substreams:
        start_block: 0
