schema_version: 1
environment: dev
updated_at: "2026-07-10"
protocol:
  name: xarb
  release: v0.1.0
hub:
  chain_id: 84532
  name: base-sepolia
  role: hub
  native_symbol: ETH
  explorer_url: https://sepolia.basescan.org
  contracts:
    hub:
      address: "0xc9AE553Ce2a7EdcBeDFe1D502515ebC643720B31"
    oracle:
      address: "0x69260D664125C111E2b894CA77a2E48Cd0E94e7c"
spokes:
  - chain_id: 84532
    name: base-sepolia
    role: spoke
    native_symbol: ETH
    explorer_url: https://sepolia.basescan.org
    contracts:
      spoke:
        address: "0xb4b8F672bCB656a5fBFF5F91878CcE32eaeC926E"
      lending_pool:
        address: "0xAc2fd13de8B94095515e079D486f759836cCCc69"
    substreams:
      start_block: 0
